#!/bin/sh

[ "$UID" != 0 ] && su=sudo

country='US'
url="https://www.archlinux.org/mirrorlist/?country=US&protocol=ftp&protocol=http&protocol=https&ip_version=4&ip_version=6&use_mirror_status=on"

tmpfile=$(mktemp --suffix=-mirrorlist)
mirrorlist=/etc/pacman.d/aw_mirrorlist

# Get latest mirror list and save to tmpfile
wget -qO- "$url" | sed 's/^#Server/Server/g' > "$tmpfile"

# Backup and replace current mirrorlist file (if new file is non-zero)
if [ -s "$tmpfile" ]
then 
        { echo " Backing up the original mirrorlist..."
          $su mv -i "$mirrorlist" "$mirrorlist".orig;
	} &&
        { echo " Rotating the new list into place..."
          $su mv -i "$tmpfile" "$mirrorlist"; 
        }
else
        echo " Unable to update, could not download list."
fi

# allow global read access (required for non-root yaourt execution)
chmod +r "$mirrorlist"
